#cleanup

rm -rf obj_dir
rm -f sigdelay.vcd

#Run the verilator to translate .sv (Verilog) into c++, including c++ testbench

verilator -Wall --cc --trace sigdelay.sv --exe sigdelay_tb.cpp

#build c++ project automaticlaly, using "make", generated by verilator

make -j -C obj_dir/ -f Vsigdelay.mk Vsigdelay

#run executable

obj_dir/Vsigdelay