#cleanup

rm -rf obj_dir
rm -f counter.vcd

#Run the verilator to translate .sv (Verilog) into c++, including c++ testbench

verilator -Wall --cc --trace counter.sv --exe counter_tb.cpp

#build c++ project automaticlaly, using "make", generated by verilator



#run executable

obj_dir/Vcounter
